# Fork ben02的主题进行修改
# https://github.com/Ben02/hexo-theme-Anatole

keywords: NBA,播客,NBA视频
author: Max # 用户信息
description: YouTube NBA精彩视频播客! # 个人介绍
avatar: /images/favicon.ico

#canvas nest
canvas_nest: false # 动态背景，true改为启用

# Social Accounts
# 整个url

# 评论
duoshuo:
disqus:
gentie:
livere:
  enable: false
  id: city
  uid:

# Valine comments : https://valine.js.org
valine:
  enable: false # if you want use valine, please set enable: true
  appid: # your leancloud appid
  appkey: # your leancloud appkey
  notify: false # true/false:mail notify !!!Test,Caution. https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
  verify: false # true/false:verify code
  avatar: mm # avatar style https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
  placeholder: Just go go # comment box placeholder

daovoice:
  enable: false
  appid:

notice: 本博客所有视频归NBA（美国职业篮球联赛）及视频制作方所有，视频仅做学习之用，不得用于商业行为！

reward_settings:
  enable: true
  comment:

reward:
  alipay:
    path: /images/alipay.jpg
    color: "#00A3EE"
    icon: icon-alipay-line
  wechat-pay:
    path: /images/wechatpay.jpg
    color: "#2DC100"
    icon: icon-wechat-pay-line
